name: GitHub Metrics

on:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate calendar metrics
        uses: lowlighter/metrics@latest
        with:
          user: vivek2124-vb
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.plugin.calendar.svg
          plugin_calendar: yes
          plugin_calendar_limit: 1

      - name: Show generated files
        run: ls -la

      - name: Commit generated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github metrics"
